<?php 
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JogadoresParte3TableSeeder extends Seeder
{
   /**
   * Run the database seeds.
   *
   * @return void
   */
   public function run()
   {
       DB::table('jogadores')->insert([
           'id' => '209', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '22', 
           'ds_nome' => 'Diogo Costa', 
           'ds_abreviado' => 'Diogo Costa', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Futebol Clube do Porto', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2019', 
           'nr_fim_random' => '2028', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '210', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '12', 
           'ds_nome' => 'José Sá', 
           'ds_abreviado' => 'José Sá', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Wolverhampton Wanderers', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2029', 
           'nr_fim_random' => '2038', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '211', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '1', 
           'ds_nome' => 'Rui Patrício', 
           'ds_abreviado' => 'Rui Patrício', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Roma', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2039', 
           'nr_fim_random' => '2048', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '212', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '4', 
           'ds_nome' => 'Rúben Dias', 
           'ds_abreviado' => 'Rúben Dias', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2049', 
           'nr_fim_random' => '2058', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '213', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '26', 
           'ds_nome' => 'António Silva', 
           'ds_abreviado' => 'António Silva', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sport Lisboa e Benfica', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2059', 
           'nr_fim_random' => '2068', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '214', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '3', 
           'ds_nome' => 'Pepe', 
           'ds_abreviado' => 'Pepe ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Futebol Clube do Porto', 
           'ds_valor' => '1,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2069', 
           'nr_fim_random' => '2078', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '215', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '5', 
           'ds_nome' => 'Raphaël Guerreiro', 
           'ds_abreviado' => 'Raphaël Guerreiro', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2079', 
           'nr_fim_random' => '2088', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '216', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '20', 
           'ds_nome' => 'João Cancelo', 
           'ds_abreviado' => 'João Cancelo', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2089', 
           'nr_fim_random' => '2098', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '217', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '2', 
           'ds_nome' => 'Diogo Dalot', 
           'ds_abreviado' => 'Diogo Dalot ', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '32,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2099', 
           'nr_fim_random' => '2108', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '218', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '18', 
           'ds_nome' => 'Rúben Neves', 
           'ds_abreviado' => 'Rúben Neves', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Wolverhampton Wanderers', 
           'ds_valor' => '40,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2109', 
           'nr_fim_random' => '2118', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '219', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '6', 
           'ds_nome' => 'João Palhinha', 
           'ds_abreviado' => 'João Palhinha', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Fulham', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2119', 
           'nr_fim_random' => '2128', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '220', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '14', 
           'ds_nome' => 'William Carvalho', 
           'ds_abreviado' => 'William Carvalho', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Bétis', 
           'ds_valor' => '16,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2129', 
           'nr_fim_random' => '2138', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '221', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '13', 
           'ds_nome' => 'Danilo Pereira', 
           'ds_abreviado' => 'Danilo Pereira', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '12,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2139', 
           'nr_fim_random' => '2148', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '222', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '11', 
           'ds_nome' => 'Matheus Nunes', 
           'ds_abreviado' => 'Matheus Nunes ', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Wolverhampton Wanderers', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2149', 
           'nr_fim_random' => '2158', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '223', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '24', 
           'ds_nome' => 'Vitinha', 
           'ds_abreviado' => 'Vitinha', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2159', 
           'nr_fim_random' => '2168', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '224', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '17', 
           'ds_nome' => 'João Mário', 
           'ds_abreviado' => 'João Mário', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sport Lisboa e Benfica', 
           'ds_valor' => '12,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2169', 
           'nr_fim_random' => '2178', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '225', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '16', 
           'ds_nome' => 'Otávio', 
           'ds_abreviado' => 'Otávio', 
           'ds_posicao' => 'Meia Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Futebol Clube do Porto', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2179', 
           'nr_fim_random' => '2188', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '226', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '25', 
           'ds_nome' => 'Nuno Mendes', 
           'ds_abreviado' => 'Nuno Mendes', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2189', 
           'nr_fim_random' => '2198', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '227', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '10', 
           'ds_nome' => 'Bernardo Silva', 
           'ds_abreviado' => 'Bernardo Silva', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '80,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2199', 
           'nr_fim_random' => '2204', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '228', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '8', 
           'ds_nome' => 'Bruno Fernandes', 
           'ds_abreviado' => 'Bruno Fernandes', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2205', 
           'nr_fim_random' => '2210', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '229', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '15', 
           'ds_nome' => 'Rafael Leão', 
           'ds_abreviado' => 'Rafael Leão', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AC Milan', 
           'ds_valor' => '70,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2211', 
           'nr_fim_random' => '2216', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '230', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '21', 
           'ds_nome' => 'Ricardo Horta', 
           'ds_abreviado' => 'Ricardo Horta', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sporting Clube de Braga', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2217', 
           'nr_fim_random' => '2226', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '231', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '23', 
           'ds_nome' => 'João Félix', 
           'ds_abreviado' => 'João Félix', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atlético de Madrid', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2227', 
           'nr_fim_random' => '2236', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '232', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '9', 
           'ds_nome' => 'André Silva', 
           'ds_abreviado' => 'André Silva', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RB Leipzig', 
           'ds_valor' => '24,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2237', 
           'nr_fim_random' => '2246', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '233', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '19', 
           'ds_nome' => 'Gonçalo Ramos', 
           'ds_abreviado' => 'Gonçalo Ramos ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sport Lisboa e Benfica', 
           'ds_valor' => '24,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2247', 
           'nr_fim_random' => '2256', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '234', 
           'id_selecao' => '29', 
           'ds_selecao' => 'Portugal', 
           'ds_numero' => '7', 
           'ds_nome' => 'Cristiano Ronaldo', 
           'ds_abreviado' => 'Cristiano Ronaldo ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2257', 
           'nr_fim_random' => '2259', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '235', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '23', 
           'ds_nome' => 'Alfred Gomis', 
           'ds_abreviado' => 'Alfred Gomis', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Stade Rennais FC', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2260', 
           'nr_fim_random' => '2269', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '236', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '1', 
           'ds_nome' => 'Seny Dieng', 
           'ds_abreviado' => 'Seny Dieng', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Queens Park Rangers', 
           'ds_valor' => '1,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2270', 
           'nr_fim_random' => '2279', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '237', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '28', 
           'ds_nome' => 'Mory Diaw', 
           'ds_abreviado' => 'Mory Diaw', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Clermont Foot 63', 
           'ds_valor' => '1,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2280', 
           'nr_fim_random' => '2289', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '28', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '238', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '3', 
           'ds_nome' => 'Kalidou Koulibaly', 
           'ds_abreviado' => 'Kalidou Koulibaly ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2290', 
           'nr_fim_random' => '2299', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '239', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '19', 
           'ds_nome' => 'Moussa Niakhaté', 
           'ds_abreviado' => 'Moussa Niakhaté ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nottingham Forest', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2300', 
           'nr_fim_random' => '2309', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '240', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '22', 
           'ds_nome' => 'Abdou Diallo', 
           'ds_abreviado' => 'Abdou Diallo', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RB Leipzig', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2310', 
           'nr_fim_random' => '2319', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '241', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '4', 
           'ds_nome' => 'Pape Abou Cissé', 
           'ds_abreviado' => 'Pape Abou Cissé', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Olympiacos Pireu', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2320', 
           'nr_fim_random' => '2329', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '242', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '2', 
           'ds_nome' => 'Formose Mendy', 
           'ds_abreviado' => 'Formose Mendy', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Amiens SC', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2330', 
           'nr_fim_random' => '2339', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '243', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '13', 
           'ds_nome' => 'Ismail Jakobs', 
           'ds_abreviado' => 'Ismail Jakobs', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Mônaco', 
           'ds_valor' => '7,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2340', 
           'nr_fim_random' => '2349', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '244', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '12', 
           'ds_nome' => 'Fodé Ballo-Touré', 
           'ds_abreviado' => 'Fodé Ballo-Touré', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AC Milan', 
           'ds_valor' => '3,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2350', 
           'nr_fim_random' => '2359', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '245', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '26', 
           'ds_nome' => 'Pape Gueye', 
           'ds_abreviado' => 'Pape Gueye', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Olympique Marselha', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2360', 
           'nr_fim_random' => '2369', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '246', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '6', 
           'ds_nome' => 'Nampalys Mendy', 
           'ds_abreviado' => 'Nampalys Mendy', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Leicester City FC', 
           'ds_valor' => '3,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2370', 
           'nr_fim_random' => '2379', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '247', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '25', 
           'ds_nome' => 'Mamadou Loum', 
           'ds_abreviado' => 'Mamadou Loum', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Reading', 
           'ds_valor' => '3,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2380', 
           'nr_fim_random' => '2389', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '248', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '8', 
           'ds_nome' => 'Cheikhou Kouyaté', 
           'ds_abreviado' => 'Cheikhou Kouyaté', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nottingham Forest', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2390', 
           'nr_fim_random' => '2399', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '249', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '17', 
           'ds_nome' => 'Pape Matar Sarr', 
           'ds_abreviado' => 'Pape Matar Sarr', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2400', 
           'nr_fim_random' => '2409', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '250', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '5', 
           'ds_nome' => 'Idrissa Gueye', 
           'ds_abreviado' => 'Idrissa Gueye', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Everton', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2410', 
           'nr_fim_random' => '2419', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '251', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '11', 
           'ds_nome' => 'Pathé Ciss', 
           'ds_abreviado' => 'Pathé Ciss', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Rayo Vallecano', 
           'ds_valor' => '4,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2420', 
           'nr_fim_random' => '2429', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '252', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '24', 
           'ds_nome' => 'Moustapha Name', 
           'ds_abreviado' => 'Moustapha Name', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Pafos FC', 
           'ds_valor' => '2,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2430', 
           'nr_fim_random' => '2439', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '253', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '21', 
           'ds_nome' => 'Iliman Ndiaye', 
           'ds_abreviado' => 'Iliman Ndiaye', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sheffield United', 
           'ds_valor' => '3,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2440', 
           'nr_fim_random' => '2449', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '254', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '10', 
           'ds_nome' => 'Sadio Mané', 
           'ds_abreviado' => 'Sadio Mané ', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2450', 
           'nr_fim_random' => '2459', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '255', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '18', 
           'ds_nome' => 'Ismaïla Sarr', 
           'ds_abreviado' => 'Ismaïla Sarr', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Watford', 
           'ds_valor' => '22,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2460', 
           'nr_fim_random' => '2469', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '256', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '27', 
           'ds_nome' => 'Nicolas Jackson', 
           'ds_abreviado' => 'Nicolas Jackson', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Villarreal', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2470', 
           'nr_fim_random' => '2479', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '27', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '257', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '15', 
           'ds_nome' => 'Krépin Diatta', 
           'ds_abreviado' => 'Krépin Diatta', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Mônaco', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2480', 
           'nr_fim_random' => '2489', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '258', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '29', 
           'ds_nome' => 'Demba Seck', 
           'ds_abreviado' => 'Demba Seck', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Torino FC', 
           'ds_valor' => '3,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2490', 
           'nr_fim_random' => '2499', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '29', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '259', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '9', 
           'ds_nome' => 'Boulaye Dia', 
           'ds_abreviado' => 'Boulaye Dia', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Salernitana Calcio 1919', 
           'ds_valor' => '12,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2500', 
           'nr_fim_random' => '2509', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '260', 
           'id_selecao' => '28', 
           'ds_selecao' => 'Camarões', 
           'ds_numero' => '20', 
           'ds_nome' => 'Bamba Dieng', 
           'ds_abreviado' => 'Bamba Dieng', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Olympique Marselha', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2510', 
           'nr_fim_random' => '2519', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '261', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '12', 
           'ds_nome' => 'Predrag Rajković', 
           'ds_abreviado' => 'Predrag Rajković ', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RCD Mallorca', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2520', 
           'nr_fim_random' => '2529', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '262', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '1', 
           'ds_nome' => 'Marko Dmitrović', 
           'ds_abreviado' => 'Marko Dmitrović', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2530', 
           'nr_fim_random' => '2539', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '263', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '23', 
           'ds_nome' => 'Vanja Milinković-Savić', 
           'ds_abreviado' => 'Vanja Milinković-Savić', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Torino FC', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2540', 
           'nr_fim_random' => '2549', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '264', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '2', 
           'ds_nome' => 'Strahinja Pavlovic', 
           'ds_abreviado' => 'Strahinja Pavlovic', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Red Bull Salzburgo', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2550', 
           'nr_fim_random' => '2559', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '265', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '4', 
           'ds_nome' => 'Nikola Milenković', 
           'ds_abreviado' => 'Nikola Milenković', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'ACF Fiorentina', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2560', 
           'nr_fim_random' => '2569', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '266', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '5', 
           'ds_nome' => 'Milos Veljkovic', 
           'ds_abreviado' => 'Milos Veljkovic ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Werder Bremen', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2570', 
           'nr_fim_random' => '2579', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '267', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '25', 
           'ds_nome' => 'Strahinja Erakovic', 
           'ds_abreviado' => 'Strahinja Erakovic', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Estrela Vermelha de Belgrado', 
           'ds_valor' => '5,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2580', 
           'nr_fim_random' => '2589', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '268', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '26', 
           'ds_nome' => 'Srdjan Babic', 
           'ds_abreviado' => 'Srdjan Babic', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'UD Almería', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2590', 
           'nr_fim_random' => '2599', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '269', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '13', 
           'ds_nome' => 'Stefan Mitrović', 
           'ds_abreviado' => 'Stefan Mitrović', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Getafe CF', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2600', 
           'nr_fim_random' => '2609', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '270', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '6', 
           'ds_nome' => 'Nemanja Maksimović', 
           'ds_abreviado' => 'Nemanja Maksimović', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Getafe CF', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2610', 
           'nr_fim_random' => '2619', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '271', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '15', 
           'ds_nome' => 'Marko Grujic', 
           'ds_abreviado' => 'Marko Grujic', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Futebol Clube do Porto', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2620', 
           'nr_fim_random' => '2629', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '272', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '24', 
           'ds_nome' => 'Uroš Račić', 
           'ds_abreviado' => 'Uroš Račić', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sporting Clube de Braga', 
           'ds_valor' => '6,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2630', 
           'nr_fim_random' => '2639', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '273', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '8', 
           'ds_nome' => 'Nemanja Gudelj', 
           'ds_abreviado' => 'Nemanja Gudelj', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '4,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2640', 
           'nr_fim_random' => '2649', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '274', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '20', 
           'ds_nome' => 'ergej Milinković-Savić', 
           'ds_abreviado' => 'Sergej Milinković-Savić', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SS Lazio', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2650', 
           'nr_fim_random' => '2659', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '275', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '16', 
           'ds_nome' => 'Saša Lukić', 
           'ds_abreviado' => 'Saša Lukić ', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Torino FC', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2660', 
           'nr_fim_random' => '2669', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '276', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '19', 
           'ds_nome' => 'Ivan Ilic', 
           'ds_abreviado' => 'Ivan Ilic', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Hellas Verona', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2670', 
           'nr_fim_random' => '2679', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '277', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '17', 
           'ds_nome' => 'Filip Kostic', 
           'ds_abreviado' => 'Filip Kostic', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '24,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2680', 
           'nr_fim_random' => '2689', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '278', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '22', 
           'ds_nome' => 'Darko Lazović', 
           'ds_abreviado' => 'Darko Lazović', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Hellas Verona', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2690', 
           'nr_fim_random' => '2699', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '279', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '3', 
           'ds_nome' => 'Filip Mladenovic', 
           'ds_abreviado' => 'Filip Mladenovic', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Legia de Varsóvia', 
           'ds_valor' => '1,20 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2700', 
           'nr_fim_random' => '2709', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '280', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '21', 
           'ds_nome' => 'Filip Djuricic', 
           'ds_abreviado' => 'Filip Djuricic', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'UC Sampdoria', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2710', 
           'nr_fim_random' => '2719', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '281', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '10', 
           'ds_nome' => 'Dusan Tadić', 
           'ds_abreviado' => 'Dusan Tadić ', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AFC Ajax', 
           'ds_valor' => '7,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2720', 
           'nr_fim_random' => '2729', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '282', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '7', 
           'ds_nome' => 'Nemanja Radonjić', 
           'ds_abreviado' => 'Nemanja Radonjić', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Torino FC', 
           'ds_valor' => '4,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2730', 
           'nr_fim_random' => '2739', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '283', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '14', 
           'ds_nome' => 'Andrija Zivkovic', 
           'ds_abreviado' => 'Andrija Zivkovic', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'PAOK Thessaloniki', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2740', 
           'nr_fim_random' => '2749', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '284', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '18', 
           'ds_nome' => 'Dušan Vlahović', 
           'ds_abreviado' => 'Dušan Vlahović ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '80,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2750', 
           'nr_fim_random' => '2752', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '285', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '9', 
           'ds_nome' => 'Aleksandar Mitrović', 
           'ds_abreviado' => 'Aleksandar Mitrović ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Fulham', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2753', 
           'nr_fim_random' => '2762', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '286', 
           'id_selecao' => '26', 
           'ds_selecao' => 'Sérvia', 
           'ds_numero' => '11', 
           'ds_nome' => 'Luka Jović', 
           'ds_abreviado' => 'Luka Jović', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'ACF Fiorentina', 
           'ds_valor' => '14,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2763', 
           'nr_fim_random' => '2772', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '287', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '23', 
           'ds_nome' => 'Sergio Rochet', 
           'ds_abreviado' => 'Sergio Rochet', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Club Nacional', 
           'ds_valor' => '3,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2773', 
           'nr_fim_random' => '2782', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '288', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '1', 
           'ds_nome' => 'Fernando Muslera', 
           'ds_abreviado' => 'Fernando Muslera', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Galatasaray', 
           'ds_valor' => '1,70 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2783', 
           'nr_fim_random' => '2792', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '289', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '12', 
           'ds_nome' => 'Sebastián Sosa', 
           'ds_abreviado' => 'Sebastián Sosa', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CA Independiente', 
           'ds_valor' => '800 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2793', 
           'nr_fim_random' => '2802', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '290', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '4', 
           'ds_nome' => 'Ronald Araújo', 
           'ds_abreviado' => 'Ronald Araújo ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Barcelona', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2803', 
           'nr_fim_random' => '2812', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '291', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '2', 
           'ds_nome' => 'José María Giménez', 
           'ds_abreviado' => 'José María Giménez', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atlético de Madrid', 
           'ds_valor' => '40,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2813', 
           'nr_fim_random' => '2822', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '292', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '19', 
           'ds_nome' => 'Sebastián Coates', 
           'ds_abreviado' => 'Sebastián Coates', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sporting Clube de Portugal', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2823', 
           'nr_fim_random' => '2832', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '293', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '3', 
           'ds_nome' => 'Diego Godín', 
           'ds_abreviado' => 'Diego Godín', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CA Vélez Sarsfield', 
           'ds_valor' => '700 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2833', 
           'nr_fim_random' => '2842', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '294', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '22', 
           'ds_nome' => 'Martín Cáceres', 
           'ds_abreviado' => 'Martín Cáceres', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Los Angeles Galaxy', 
           'ds_valor' => '500 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2843', 
           'nr_fim_random' => '2852', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '295', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '16', 
           'ds_nome' => 'Mathías Olivera', 
           'ds_abreviado' => 'Mathías Olivera', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Napoli', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2853', 
           'nr_fim_random' => '2862', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '296', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '17', 
           'ds_nome' => 'Matías Viña', 
           'ds_abreviado' => 'Matías Viña', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Roma', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2863', 
           'nr_fim_random' => '2872', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '297', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '20', 
           'ds_nome' => 'Guillermo Varela', 
           'ds_abreviado' => 'Guillermo Varela', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CR Flamengo', 
           'ds_valor' => '2,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2873', 
           'nr_fim_random' => '2882', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '298', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '13', 
           'ds_nome' => 'José Luis Rodríguez', 
           'ds_abreviado' => 'José Luis Rodríguez', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Club Nacional', 
           'ds_valor' => '850 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2883', 
           'nr_fim_random' => '2892', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '299', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '25', 
           'ds_nome' => 'Manuel Ugarte', 
           'ds_abreviado' => 'Manuel Ugarte', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sporting Clube de Portugal', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2893', 
           'nr_fim_random' => '2902', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '300', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '14', 
           'ds_nome' => 'Lucas Torreira', 
           'ds_abreviado' => 'Lucas Torreira', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Galatasaray', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2903', 
           'nr_fim_random' => '2912', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '301', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '15', 
           'ds_nome' => 'Federico Valverde', 
           'ds_abreviado' => 'Federico Valverde', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '100,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2913', 
           'nr_fim_random' => '2918', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '302', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '6', 
           'ds_nome' => 'Rodrigo Bentancur', 
           'ds_abreviado' => 'Rodrigo Bentancur', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '40,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2919', 
           'nr_fim_random' => '2928', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '303', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '7', 
           'ds_nome' => 'Nicolás de la Cruz', 
           'ds_abreviado' => 'Nicolás de la Cruz', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CA River Plate', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2929', 
           'nr_fim_random' => '2938', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '304', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '5', 
           'ds_nome' => 'Matías Vecino', 
           'ds_abreviado' => 'Matías Vecino', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SS Lazio', 
           'ds_valor' => '4,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2939', 
           'nr_fim_random' => '2948', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '305', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '10', 
           'ds_nome' => 'Giorgian de Arrascaeta', 
           'ds_abreviado' => 'Giorgian de Arrascaeta', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CR Flamengo', 
           'ds_valor' => '18,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2949', 
           'nr_fim_random' => '2958', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '306', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '26', 
           'ds_nome' => 'Facundo Torres', 
           'ds_abreviado' => 'Facundo Torres', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Orlando City SC', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2959', 
           'nr_fim_random' => '2968', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '307', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '24', 
           'ds_nome' => 'Agustín Canobbio', 
           'ds_abreviado' => 'Agustín Canobbio', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Athletico Paranaense', 
           'ds_valor' => '4,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2969', 
           'nr_fim_random' => '2978', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '308', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '8', 
           'ds_nome' => 'Facundo Pellistri', 
           'ds_abreviado' => 'Facundo Pellistri', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2979', 
           'nr_fim_random' => '2988', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '309', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '11', 
           'ds_nome' => 'Darwin Núñez', 
           'ds_abreviado' => 'Darwin Núñez', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Liverpool', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2989', 
           'nr_fim_random' => '2998', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '310', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '9', 
           'ds_nome' => 'Luis Suárez', 
           'ds_abreviado' => 'Luis Suárez ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Club Nacional', 
           'ds_valor' => '8,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2999', 
           'nr_fim_random' => '3008', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '311', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '18', 
           'ds_nome' => 'Maxi Gómez', 
           'ds_abreviado' => 'Maxi Gómez', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Trabzonspor', 
           'ds_valor' => '7,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3009', 
           'nr_fim_random' => '3018', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '312', 
           'id_selecao' => '31', 
           'ds_selecao' => 'Uruguai', 
           'ds_numero' => '21', 
           'ds_nome' => 'Edinson Cavani', 
           'ds_abreviado' => 'Edinson Cavani ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Valência CF', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3019', 
           'nr_fim_random' => '3028', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '313', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '23', 
           'ds_nome' => 'Emiliano Martínez', 
           'ds_abreviado' => 'Emiliano Martínez', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Aston Villa FC', 
           'ds_valor' => '25,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3029', 
           'nr_fim_random' => '3038', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '314', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '12', 
           'ds_nome' => 'Gerónimo Rulli', 
           'ds_abreviado' => 'Gerónimo Rulli', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Villarreal', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3039', 
           'nr_fim_random' => '3048', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '315', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '1', 
           'ds_nome' => 'Franco Armani', 
           'ds_abreviado' => 'Franco Armani', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CA River Plate', 
           'ds_valor' => '3,20 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3049', 
           'nr_fim_random' => '3058', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '316', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '13', 
           'ds_nome' => 'Cristian Romero', 
           'ds_abreviado' => 'Cristian Romero ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '55,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3059', 
           'nr_fim_random' => '3068', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '317', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '16', 
           'ds_nome' => 'Lisandro Martínez', 
           'ds_abreviado' => 'Lisandro Martínez ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3069', 
           'nr_fim_random' => '3078', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '318', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '6', 
           'ds_nome' => 'Germán Pezzella', 
           'ds_abreviado' => 'Germán Pezzella', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Bétis', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3079', 
           'nr_fim_random' => '3088', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '319', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '19', 
           'ds_nome' => 'Nicolás Otamendi', 
           'ds_abreviado' => 'Nicolás Otamendi', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sport Lisboa e Benfica', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3089', 
           'nr_fim_random' => '3098', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '320', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '8', 
           'ds_nome' => 'Marcos Acuña', 
           'ds_abreviado' => 'Marcos Acuña', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '14,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3099', 
           'nr_fim_random' => '3108', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '321', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '3', 
           'ds_nome' => 'Nicolás Tagliafico', 
           'ds_abreviado' => 'Nicolás Tagliafico', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Olympique Lyon', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3109', 
           'nr_fim_random' => '3118', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '322', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '2', 
           'ds_nome' => 'Juan Foyth', 
           'ds_abreviado' => 'Juan Foyth', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Villarreal', 
           'ds_valor' => '25,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3119', 
           'nr_fim_random' => '3128', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '323', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '26', 
           'ds_nome' => 'Nahuel Molina', 
           'ds_abreviado' => 'Nahuel Molina', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atlético de Madrid', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3129', 
           'nr_fim_random' => '3138', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '324', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '4', 
           'ds_nome' => 'Gonzalo Montiel', 
           'ds_abreviado' => 'Gonzalo Montiel', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '12,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3139', 
           'nr_fim_random' => '3148', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '325', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '18', 
           'ds_nome' => 'Guido Rodríguez', 
           'ds_abreviado' => 'Guido Rodríguez', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Bétis', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3149', 
           'nr_fim_random' => '3158', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '326', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '5', 
           'ds_nome' => 'Leandro Paredes', 
           'ds_abreviado' => 'Leandro Paredes', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3159', 
           'nr_fim_random' => '3168', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '327', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '7', 
           'ds_nome' => 'Rodrigo de Paul', 
           'ds_abreviado' => 'Rodrigo de Paul', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atlético de Madrid', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3169', 
           'nr_fim_random' => '3178', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '328', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '24', 
           'ds_nome' => 'Enzo Fernández', 
           'ds_abreviado' => 'Enzo Fernández', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sport Lisboa e Benfica', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3179', 
           'nr_fim_random' => '3188', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '329', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '15', 
           'ds_nome' => 'Alexis Mac Allister', 
           'ds_abreviado' => 'Alexis Mac Allister', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Brighton & Hove Albion', 
           'ds_valor' => '32,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3189', 
           'nr_fim_random' => '3198', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '330', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '14', 
           'ds_nome' => 'Exequiel Palacios', 
           'ds_abreviado' => 'Exequiel Palacios', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Bayer 04 Leverkusen', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3199', 
           'nr_fim_random' => '3208', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '331', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '25', 
           'ds_nome' => 'Nicolás González', 
           'ds_abreviado' => 'Nicolás González', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'ACF Fiorentina', 
           'ds_valor' => '23,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3209', 
           'nr_fim_random' => '3218', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '332', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '20', 
           'ds_nome' => 'Papu Gómez', 
           'ds_abreviado' => 'Papu Gómez', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '4,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3219', 
           'nr_fim_random' => '3228', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '333', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '11', 
           'ds_nome' => 'Ángel Di María', 
           'ds_abreviado' => 'Ángel Di María', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3229', 
           'nr_fim_random' => '3238', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '334', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '10', 
           'ds_nome' => 'Lionel Messi', 
           'ds_abreviado' => 'Lionel Messi ', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3239', 
           'nr_fim_random' => '3241', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '335', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '21', 
           'ds_nome' => 'Paulo Dybala', 
           'ds_abreviado' => 'Paulo Dybala ', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Roma', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3242', 
           'nr_fim_random' => '3251', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '336', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '17', 
           'ds_nome' => 'Joaquín Correa', 
           'ds_abreviado' => 'Joaquín Correa', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Inter de Milão', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3252', 
           'nr_fim_random' => '3261', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '337', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '22', 
           'ds_nome' => 'Lautaro Martínez', 
           'ds_abreviado' => 'Lautaro Martínez', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Inter de Milão', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3262', 
           'nr_fim_random' => '3267', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '338', 
           'id_selecao' => '9', 
           'ds_selecao' => 'Argentina', 
           'ds_numero' => '9', 
           'ds_nome' => 'Julián Álvarez', 
           'ds_abreviado' => 'Julián Álvarez', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '32,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '3268', 
           'nr_fim_random' => '3277', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
   }
}