<?php 
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JogadoresTableSeeder extends Seeder
{
   /**
   * Run the database seeds.
   *
   * @return void
   */
   public function run()
   {       
       DB::table('jogadores')->insert([
           'id' => '1', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '1', 
           'ds_nome' => 'Alisson', 
           'ds_abreviado' => 'Alisson', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Liverpool', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1', 
           'nr_fim_random' => '10', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '2', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '23', 
           'ds_nome' => 'Ederson', 
           'ds_abreviado' => 'Ederson', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '11', 
           'nr_fim_random' => '20', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '3', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '12', 
           'ds_nome' => 'Weverton', 
           'ds_abreviado' => 'Weverton', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SE Palmeiras', 
           'ds_valor' => '4,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '21', 
           'nr_fim_random' => '30', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '4', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '4', 
           'ds_nome' => 'Marquinhos', 
           'ds_abreviado' => 'Marquinhos', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '31', 
           'nr_fim_random' => '40', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '5', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '14', 
           'ds_nome' => 'Éder Militão', 
           'ds_abreviado' => 'Éder Militão', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '41', 
           'nr_fim_random' => '50', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '6', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '22', 
           'ds_nome' => 'Bremer', 
           'ds_abreviado' => 'Bremer', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '40,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '51', 
           'nr_fim_random' => '60', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '7', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '3', 
           'ds_nome' => 'Thiago Silva', 
           'ds_abreviado' => 'Thiago Silva ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '61', 
           'nr_fim_random' => '70', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '8', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '16', 
           'ds_nome' => 'Alex Telles', 
           'ds_abreviado' => 'Alex Telles', 
           'ds_posicao' => 'Lateral Esquerdo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sevilla FC', 
           'ds_valor' => '14,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '71', 
           'nr_fim_random' => '80', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '9', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '6', 
           'ds_nome' => 'Alex Sandro', 
           'ds_abreviado' => 'Alex Sandro', 
           'ds_posicao' => 'Lateral Esquerdo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '81', 
           'nr_fim_random' => '90', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '10', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '2', 
           'ds_nome' => 'Danilo', 
           'ds_abreviado' => 'Danilo', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '13,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '91', 
           'nr_fim_random' => '100', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '11', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '13', 
           'ds_nome' => 'Dani Alves', 
           'ds_abreviado' => 'Dani Alves', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'UNAM Pumas', 
           'ds_valor' => '1,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '101', 
           'nr_fim_random' => '110', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '12', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '17', 
           'ds_nome' => 'Bruno Guimarães', 
           'ds_abreviado' => 'Bruno Guimarães', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Newcastle United', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '111', 
           'nr_fim_random' => '120', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '13', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '15', 
           'ds_nome' => 'Fabinho', 
           'ds_abreviado' => 'Fabinho', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Liverpool', 
           'ds_valor' => '55,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '121', 
           'nr_fim_random' => '126', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '14', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '5', 
           'ds_nome' => 'Casemiro', 
           'ds_abreviado' => 'Casemiro', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '127', 
           'nr_fim_random' => '132', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '15', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '8', 
           'ds_nome' => 'Fred', 
           'ds_abreviado' => 'Fred', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '133', 
           'nr_fim_random' => '142', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '16', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '26', 
           'ds_nome' => 'Éverton Ribeiro', 
           'ds_abreviado' => 'Éverton Ribeiro', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CR Flamengo', 
           'ds_valor' => '4,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '143', 
           'nr_fim_random' => '152', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '17', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '7', 
           'ds_nome' => 'Lucas Paquetá', 
           'ds_abreviado' => 'Lucas Paquetá', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'West Ham United', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '153', 
           'nr_fim_random' => '162', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '18', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '20', 
           'ds_nome' => 'Vinicius Junior', 
           'ds_abreviado' => 'Vinicius Junior', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '120,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '163', 
           'nr_fim_random' => '165', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '19', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '10', 
           'ds_nome' => 'Neymar', 
           'ds_abreviado' => 'Neymar', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '166', 
           'nr_fim_random' => '168', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '20', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '24', 
           'ds_nome' => 'Gabriel Martinelli', 
           'ds_abreviado' => 'Gabriel Martinelli', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '169', 
           'nr_fim_random' => '178', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '21', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '21', 
           'ds_nome' => 'Rodrygo', 
           'ds_abreviado' => 'Rodrygo', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '80,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '179', 
           'nr_fim_random' => '188', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '22', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '18', 
           'ds_nome' => 'Antony', 
           'ds_abreviado' => 'Antony', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '189', 
           'nr_fim_random' => '198', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '23', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '11', 
           'ds_nome' => 'Raphinha', 
           'ds_abreviado' => 'Raphinha', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Barcelona', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '199', 
           'nr_fim_random' => '208', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '24', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '19', 
           'ds_nome' => 'Gabriel Jesus', 
           'ds_abreviado' => 'Gabriel Jesus', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '209', 
           'nr_fim_random' => '218', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '25', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '9', 
           'ds_nome' => 'Richarlison', 
           'ds_abreviado' => 'Richarlison ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '50,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '219', 
           'nr_fim_random' => '228', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '26', 
           'id_selecao' => '25', 
           'ds_selecao' => 'Brasil', 
           'ds_numero' => '25', 
           'ds_nome' => 'Pedro', 
           'ds_abreviado' => 'Pedro', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CR Flamengo', 
           'ds_valor' => '12,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '229', 
           'nr_fim_random' => '238', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '27', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '1', 
           'ds_nome' => 'Keylor Navas', 
           'ds_abreviado' => 'Keylor Navas', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Paris Saint-Germain', 
           'ds_valor' => '5,00 mi. €', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '239', 
           'nr_fim_random' => '248', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '28', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '18', 
           'ds_nome' => 'Esteban Alvarado', 
           'ds_abreviado' => 'Esteban Alvarado', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '200 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '249', 
           'nr_fim_random' => '258', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '29', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '23', 
           'ds_nome' => 'Patrick Sequeira', 
           'ds_abreviado' => 'Patrick Sequeira', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CD Lugo', 
           'ds_valor' => '200 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '259', 
           'nr_fim_random' => '268', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '30', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '15', 
           'ds_nome' => 'Francisco Calvo', 
           'ds_abreviado' => 'Francisco Calvo', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Konyaspor', 
           'ds_valor' => '1,70 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '269', 
           'nr_fim_random' => '278', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '31', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '3', 
           'ds_nome' => 'Juan Pablo Vargas', 
           'ds_abreviado' => 'Juan Pablo Vargas', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Millonarios Bogotá', 
           'ds_valor' => '1,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '279', 
           'nr_fim_random' => '288', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '32', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '6', 
           'ds_nome' => 'Óscar Duarte', 
           'ds_abreviado' => 'Óscar Duarte', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Al-Wehda FC', 
           'ds_valor' => '800 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '289', 
           'nr_fim_random' => '298', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '33', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '19', 
           'ds_nome' => 'Kendall Waston', 
           'ds_abreviado' => 'Kendall Waston', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Deportivo Saprissa', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '299', 
           'nr_fim_random' => '308', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '34', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '22', 
           'ds_nome' => 'Ronald Matarrita', 
           'ds_abreviado' => 'Ronald Matarrita', 
           'ds_posicao' => 'Lateral Esquerdo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Cincinnati', 
           'ds_valor' => '2,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '309', 
           'nr_fim_random' => '318', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '35', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '8', 
           'ds_nome' => 'Bryan Oviedo', 
           'ds_abreviado' => 'Bryan Oviedo', 
           'ds_posicao' => 'Lateral Esquerdo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Salt Lake City', 
           'ds_valor' => '200 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '319', 
           'nr_fim_random' => '328', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '36', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '4', 
           'ds_nome' => 'Keysher Fuller', 
           'ds_abreviado' => 'Keysher Fuller', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '329', 
           'nr_fim_random' => '338', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '37', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '14', 
           'ds_nome' => 'Carlos Martínez', 
           'ds_abreviado' => 'Carlos Martínez', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AD San Carlos', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '339', 
           'nr_fim_random' => '348', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '38', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '2', 
           'ds_nome' => 'Daniel Chacón', 
           'ds_abreviado' => 'Daniel Chacón', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Colorado Rapids 2', 
           'ds_valor' => '300 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '349', 
           'nr_fim_random' => '358', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '39', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '17', 
           'ds_nome' => 'Yeltsin Tejeda', 
           'ds_abreviado' => 'Yeltsin Tejeda', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '275 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '359', 
           'nr_fim_random' => '368', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '40', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '24', 
           'ds_nome' => 'Douglas López', 
           'ds_abreviado' => 'Douglas López', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '275 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '369', 
           'nr_fim_random' => '378', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '41', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '16', 
           'ds_nome' => 'Youstin Salas', 
           'ds_abreviado' => 'Youstin Salas', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Deportivo Saprissa', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '379', 
           'nr_fim_random' => '388', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '42', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '5', 
           'ds_nome' => 'Celso Borges', 
           'ds_abreviado' => 'Celso Borges', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'LD Alajuelense', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '389', 
           'nr_fim_random' => '398', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '43', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '21', 
           'ds_nome' => 'Roan Wilson', 
           'ds_abreviado' => 'Roan Wilson', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Municipal Grecia', 
           'ds_valor' => '225 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '399', 
           'nr_fim_random' => '408', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '44', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '13', 
           'ds_nome' => 'Gerson Torres', 
           'ds_abreviado' => 'Gerson Torres', 
           'ds_posicao' => 'Meia Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '325 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '409', 
           'nr_fim_random' => '418', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '45', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '26', 
           'ds_nome' => 'Álvaro Zamora', 
           'ds_abreviado' => 'Álvaro Zamora', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Deportivo Saprissa', 
           'ds_valor' => ' ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '419', 
           'nr_fim_random' => '428', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '46', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '20', 
           'ds_nome' => 'Brandon Aguilera', 
           'ds_abreviado' => 'Brandon Aguilera', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AD Guanacasteca', 
           'ds_valor' => '325 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '429', 
           'nr_fim_random' => '438', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '47', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '10', 
           'ds_nome' => 'Bryan Ruiz', 
           'ds_abreviado' => 'Bryan Ruiz', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'LD Alajuelense', 
           'ds_valor' => '200 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '439', 
           'nr_fim_random' => '448', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '48', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '9', 
           'ds_nome' => 'Jewison Bennette', 
           'ds_abreviado' => 'Jewison Bennette', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AFC Sunderland', 
           'ds_valor' => '1,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '449', 
           'nr_fim_random' => '458', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '49', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '12', 
           'ds_nome' => 'Joel Campbell', 
           'ds_abreviado' => 'Joel Campbell', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Club León', 
           'ds_valor' => '2,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '459', 
           'nr_fim_random' => '468', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '50', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '25', 
           'ds_nome' => 'Anthony Hernández', 
           'ds_abreviado' => 'Anthony Hernández', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Puntarenas FC', 
           'ds_valor' => ' ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '469', 
           'nr_fim_random' => '478', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '51', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '7', 
           'ds_nome' => 'Anthony Contreras', 
           'ds_abreviado' => 'Anthony Contreras', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CS Herediano', 
           'ds_valor' => '350 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '479', 
           'nr_fim_random' => '488', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '52', 
           'id_selecao' => '18', 
           'ds_selecao' => 'Costa Rica', 
           'ds_numero' => '11', 
           'ds_nome' => 'Johan Venegas', 
           'ds_abreviado' => 'Johan Venegas', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'LD Alajuelense', 
           'ds_valor' => '325 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '489', 
           'nr_fim_random' => '498', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '53', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '23', 
           'ds_nome' => 'Daniel Schmidt', 
           'ds_abreviado' => 'Daniel Schmidt', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VV St.Truiden', 
           'ds_valor' => '1,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '499', 
           'nr_fim_random' => '508', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '54', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '12', 
           'ds_nome' => 'Shuichi Gonda', 
           'ds_abreviado' => 'Shuichi Gonda', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Shimizu S-Pulse', 
           'ds_valor' => '500 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '509', 
           'nr_fim_random' => '518', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '55', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '1', 
           'ds_nome' => 'Eiji Kawashima', 
           'ds_abreviado' => 'Eiji Kawashima', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RC Strasbourg Alsace', 
           'ds_valor' => '200 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '519', 
           'nr_fim_random' => '528', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '56', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '4', 
           'ds_nome' => 'Ko Itakura', 
           'ds_abreviado' => 'Ko Itakura ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Mönchengladbach', 
           'ds_valor' => '7,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '529', 
           'nr_fim_random' => '538', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '57', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '26', 
           'ds_nome' => 'Hiroki Ito', 
           'ds_abreviado' => 'Hiroki Ito ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VfB Stuttgart', 
           'ds_valor' => '4,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '539', 
           'nr_fim_random' => '548', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '58', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '20', 
           'ds_nome' => 'Yuta Nakayama', 
           'ds_abreviado' => 'Yuta Nakayama ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Huddersfield Town', 
           'ds_valor' => '1,80 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '549', 
           'nr_fim_random' => '558', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '59', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '3', 
           'ds_nome' => 'Shogo Taniguchi', 
           'ds_abreviado' => 'Shogo Taniguchi', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Kawasaki Frontale', 
           'ds_valor' => '1,70 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '559', 
           'nr_fim_random' => '568', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '60', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '22', 
           'ds_nome' => 'Maya Yoshida', 
           'ds_abreviado' => 'Maya Yoshida', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Schalke 04', 
           'ds_valor' => '1,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '569', 
           'nr_fim_random' => '578', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '61', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '5', 
           'ds_nome' => 'Yuto Nagatomo', 
           'ds_abreviado' => 'Yuto Nagatomo', 
           'ds_posicao' => 'Lateral Esquerdo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Tokyo', 
           'ds_valor' => '400 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '579', 
           'nr_fim_random' => '588', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '62', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '16', 
           'ds_nome' => 'Takehiro Tomiyasu', 
           'ds_abreviado' => 'Takehiro Tomiyasu', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '25,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '589', 
           'nr_fim_random' => '598', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '63', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '19', 
           'ds_nome' => 'Hiroki Sakai', 
           'ds_abreviado' => 'Hiroki Sakai', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Urawa Red Diamonds', 
           'ds_valor' => '2,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '599', 
           'nr_fim_random' => '608', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '64', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '2', 
           'ds_nome' => 'Miki Yamane', 
           'ds_abreviado' => 'Miki Yamane', 
           'ds_posicao' => 'Lateral Direito', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Kawasaki Frontale', 
           'ds_valor' => '1,30 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '609', 
           'nr_fim_random' => '618', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '65', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '6', 
           'ds_nome' => 'ataru Endo', 
           'ds_abreviado' => 'Wataru Endo', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VfB Stuttgart', 
           'ds_valor' => '8,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '619', 
           'nr_fim_random' => '628', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '66', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '13', 
           'ds_nome' => 'Hidemasa Morita', 
           'ds_abreviado' => 'Hidemasa Morita', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sporting Clube de Portugal', 
           'ds_valor' => '7,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '629', 
           'nr_fim_random' => '638', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '67', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '17', 
           'ds_nome' => 'Ao Tanaka', 
           'ds_abreviado' => 'Ao Tanaka ', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Fortuna Düsseldorf 95', 
           'ds_valor' => '1,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '639', 
           'nr_fim_random' => '648', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '68', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '7', 
           'ds_nome' => 'Gaku Shibasaki', 
           'ds_abreviado' => 'Gaku Shibasaki', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CD Leganés', 
           'ds_valor' => '1,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '649', 
           'nr_fim_random' => '658', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '69', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '15', 
           'ds_nome' => 'Daichi Kamada', 
           'ds_abreviado' => 'Daichi Kamada', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Eintracht Frankfurt', 
           'ds_valor' => '22,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '659', 
           'nr_fim_random' => '668', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '70', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '10', 
           'ds_nome' => 'Takumi Minamino', 
           'ds_abreviado' => 'Takumi Minamino', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Mônaco', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '669', 
           'nr_fim_random' => '678', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '71', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '9', 
           'ds_nome' => 'Kaoru Mitoma', 
           'ds_abreviado' => 'Kaoru Mitoma', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Brighton & Hove Albion', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '679', 
           'nr_fim_random' => '688', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '72', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '25', 
           'ds_nome' => 'Daizen Maeda', 
           'ds_abreviado' => 'Daizen Maeda', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Celtic FC', 
           'ds_valor' => '3,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '689', 
           'nr_fim_random' => '698', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '73', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '24', 
           'ds_nome' => 'Yuki Soma', 
           'ds_abreviado' => 'Yuki Soma', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nagoya Grampus', 
           'ds_valor' => '900 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '699', 
           'nr_fim_random' => '708', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '74', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '11', 
           'ds_nome' => 'Takefusa Kubo', 
           'ds_abreviado' => 'Takefusa Kubo', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Sociedad', 
           'ds_valor' => '9,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '709', 
           'nr_fim_random' => '718', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '75', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '14', 
           'ds_nome' => 'Junya Ito', 
           'ds_abreviado' => 'Junya Ito', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Stade Reims', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '719', 
           'nr_fim_random' => '728', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '76', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '8', 
           'ds_nome' => 'Ritsu Doan', 
           'ds_abreviado' => 'Ritsu Doan', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SC Freiburg', 
           'ds_valor' => '8,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '729', 
           'nr_fim_random' => '738', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '77', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '18', 
           'ds_nome' => 'Takuma Asano', 
           'ds_abreviado' => 'Takuma Asano ', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VfL Bochum', 
           'ds_valor' => '3,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '739', 
           'nr_fim_random' => '748', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '78', 
           'id_selecao' => '20', 
           'ds_selecao' => 'Japão', 
           'ds_numero' => '21', 
           'ds_nome' => 'Ayase Ueda', 
           'ds_abreviado' => 'Ayase Ueda', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Cercle Brügge', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '749', 
           'nr_fim_random' => '758', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
   }
}