<?php 
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JogadoresParte2TableSeeder extends Seeder
{
   /**
   * Run the database seeds.
   *
   * @return void
   */
   public function run()
   {
           DB::table('jogadores')->insert([
           'id' => '79', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '13', 
           'ds_nome' => 'Aaron Ramsdale', 
           'ds_abreviado' => 'Aaron Ramsdale', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '759', 
           'nr_fim_random' => '768', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '80', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '1', 
           'ds_nome' => 'Jordan Pickford', 
           'ds_abreviado' => 'Jordan Pickford', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Everton', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '769', 
           'nr_fim_random' => '778', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '81', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '22', 
           'ds_nome' => 'Nick Pope', 
           'ds_abreviado' => 'Nick Pope', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Newcastle United', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '779', 
           'nr_fim_random' => '788', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '82', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '15', 
           'ds_nome' => 'Ben White', 
           'ds_abreviado' => 'Ben White', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '789', 
           'nr_fim_random' => '798', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '83', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '4', 
           'ds_nome' => 'John Stones', 
           'ds_abreviado' => 'John Stones', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '799', 
           'nr_fim_random' => '808', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '84', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '5', 
           'ds_nome' => 'Eric Dier', 
           'ds_abreviado' => 'Eric Dier', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '809', 
           'nr_fim_random' => '818', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '85', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '6', 
           'ds_nome' => 'Harry Maguire', 
           'ds_abreviado' => 'Harry Maguire', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '819', 
           'nr_fim_random' => '828', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '86', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '16', 
           'ds_nome' => 'Conor Coady', 
           'ds_abreviado' => 'Conor Coady', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Everton', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '829', 
           'nr_fim_random' => '838', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '87', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '3', 
           'ds_nome' => 'Luke Shaw', 
           'ds_abreviado' => 'Luke Shaw', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '839', 
           'nr_fim_random' => '848', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '88', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '26', 
           'ds_nome' => 'Trent Alexander-Arnold', 
           'ds_abreviado' => 'Trent Alexander-Arnold', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Liverpool', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '849', 
           'nr_fim_random' => '858', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '89', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '2', 
           'ds_nome' => 'Kyle Walker', 
           'ds_abreviado' => 'Kyle Walker ', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '859', 
           'nr_fim_random' => '868', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '90', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '12', 
           'ds_nome' => 'Kieran Trippier', 
           'ds_abreviado' => 'Kieran Trippier', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Newcastle United', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '869', 
           'nr_fim_random' => '878', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '91', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '7', 
           'ds_nome' => 'Declan Rice', 
           'ds_abreviado' => 'Declan Rice', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'West Ham United', 
           'ds_valor' => '80,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '879', 
           'nr_fim_random' => '888', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '92', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '23', 
           'ds_nome' => 'Kalvin Phillips', 
           'ds_abreviado' => 'Kalvin Phillips', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '889', 
           'nr_fim_random' => '898', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '93', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '21', 
           'ds_nome' => 'Phil Foden', 
           'ds_abreviado' => 'Phil Foden', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '110,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '899', 
           'nr_fim_random' => '904', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '94', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '8', 
           'ds_nome' => 'Jude Bellingham', 
           'ds_abreviado' => 'Jude Bellingham', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '100,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '905', 
           'nr_fim_random' => '914', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '95', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '24', 
           'ds_nome' => 'Conor Gallagher', 
           'ds_abreviado' => 'Conor Gallagher', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '32,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '915', 
           'nr_fim_random' => '924', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '96', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '14', 
           'ds_nome' => 'Jordan Henderson', 
           'ds_abreviado' => 'Jordan Henderson', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Liverpool', 
           'ds_valor' => '15,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '925', 
           'nr_fim_random' => '934', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '97', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '18', 
           'ds_nome' => 'Bukayo Saka', 
           'ds_abreviado' => 'Bukayo Saka', 
           'ds_posicao' => 'Meia Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Arsenal', 
           'ds_valor' => '90,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '935', 
           'nr_fim_random' => '944', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '98', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '19', 
           'ds_nome' => 'Mason Mount', 
           'ds_abreviado' => 'Mason Mount', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '75,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '945', 
           'nr_fim_random' => '954', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '99', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '20', 
           'ds_nome' => 'James Maddison', 
           'ds_abreviado' => 'James Maddison', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Leicester City FC', 
           'ds_valor' => '55,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '955', 
           'nr_fim_random' => '964', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '100', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '10', 
           'ds_nome' => 'Raheem Sterling', 
           'ds_abreviado' => 'Raheem Sterling', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '965', 
           'nr_fim_random' => '974', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '101', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '17', 
           'ds_nome' => 'Jack Grealish', 
           'ds_abreviado' => 'Jack Grealish', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '975', 
           'nr_fim_random' => '984', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '102', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '11', 
           'ds_nome' => 'Marcus Rashford', 
           'ds_abreviado' => 'Marcus Rashford', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester United FC', 
           'ds_valor' => '55,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '985', 
           'nr_fim_random' => '994', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '103', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '9', 
           'ds_nome' => 'Harry Kane', 
           'ds_abreviado' => 'Harry Kane ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '90,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '995', 
           'nr_fim_random' => '997', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '104', 
           'id_selecao' => '5', 
           'ds_selecao' => 'Inglaterra', 
           'ds_numero' => '25', 
           'ds_nome' => 'Callum Wilson', 
           'ds_abreviado' => 'Callum Wilson', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Newcastle United', 
           'ds_valor' => '18,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '998', 
           'nr_fim_random' => '1007', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '105', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '12', 
           'ds_nome' => 'Danny Ward', 
           'ds_abreviado' => 'Danny Ward', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Leicester City FC', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1008', 
           'nr_fim_random' => '1017', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '106', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '1', 
           'ds_nome' => 'Wayne Hennessey', 
           'ds_abreviado' => 'Wayne Hennessey', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nottingham Forest', 
           'ds_valor' => '500 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1018', 
           'nr_fim_random' => '1027', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '107', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '21', 
           'ds_nome' => 'Adam Davies', 
           'ds_abreviado' => 'Adam Davies', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Sheffield United', 
           'ds_valor' => '500 mil €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1028', 
           'nr_fim_random' => '1037', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '108', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '15', 
           'ds_nome' => 'Ethan Ampadu', 
           'ds_abreviado' => 'Ethan Ampadu', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Spezia Calcio', 
           'ds_valor' => '13,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1038', 
           'nr_fim_random' => '1047', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '109', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '6', 
           'ds_nome' => 'Joe Rodon', 
           'ds_abreviado' => 'Joe Rodon', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Stade Rennais FC', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1048', 
           'nr_fim_random' => '1057', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '110', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '24', 
           'ds_nome' => 'Ben Cabango', 
           'ds_abreviado' => 'Ben Cabango', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Swansea City AFC', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1058', 
           'nr_fim_random' => '1067', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '111', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '5', 
           'ds_nome' => 'Chris Mepham', 
           'ds_abreviado' => 'Chris Mepham', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AFC Bournemouth', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1068', 
           'nr_fim_random' => '1077', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '112', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '22', 
           'ds_nome' => 'Tom Lockyer', 
           'ds_abreviado' => 'Tom Lockyer', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Luton Town', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1078', 
           'nr_fim_random' => '1087', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '113', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '4', 
           'ds_nome' => 'Ben Davies', 
           'ds_abreviado' => 'Ben Davies', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1088', 
           'nr_fim_random' => '1097', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '114', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '3', 
           'ds_nome' => 'Neco Williams', 
           'ds_abreviado' => 'Neco Williams', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nottingham Forest', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1098', 
           'nr_fim_random' => '1107', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '115', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '14', 
           'ds_nome' => 'Connor Roberts', 
           'ds_abreviado' => 'Connor Roberts', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Burnley', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1108', 
           'nr_fim_random' => '1117', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '116', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '2', 
           'ds_nome' => 'Chris Gunter', 
           'ds_abreviado' => 'Chris Gunter', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AFC Wimbledon', 
           'ds_valor' => '800 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1118', 
           'nr_fim_random' => '1127', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '117', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '16', 
           'ds_nome' => 'Matt Smith', 
           'ds_abreviado' => 'Matt Smith', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Milton Keynes Dons FC', 
           'ds_valor' => '450 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1128', 
           'nr_fim_random' => '1137', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '118', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '10', 
           'ds_nome' => 'Aaron Ramsey', 
           'ds_abreviado' => 'Aaron Ramsey', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'OGC Nice', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1138', 
           'nr_fim_random' => '1147', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '119', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '7', 
           'ds_nome' => 'Joe Allen', 
           'ds_abreviado' => 'Joe Allen ', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Swansea City AFC', 
           'ds_valor' => '1,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1148', 
           'nr_fim_random' => '1157', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '120', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '23', 
           'ds_nome' => 'Dylan Levitt', 
           'ds_abreviado' => 'Dylan Levitt', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Dundee United FC', 
           'ds_valor' => '700 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1158', 
           'nr_fim_random' => '1167', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '121', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '26', 
           'ds_nome' => 'Joe Morrell', 
           'ds_abreviado' => 'Joe Morrell', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Portsmouth', 
           'ds_valor' => '400 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1168', 
           'nr_fim_random' => '1177', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '122', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '25', 
           'ds_nome' => 'Rubin Colwill', 
           'ds_abreviado' => 'Rubin Colwill', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Cardiff City', 
           'ds_valor' => '1,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1178', 
           'nr_fim_random' => '1187', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '123', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '18', 
           'ds_nome' => 'Jonathan Williams', 
           'ds_abreviado' => 'Jonathan Williams', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Swindon Town FC', 
           'ds_valor' => '800 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1188', 
           'nr_fim_random' => '1197', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '124', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '8', 
           'ds_nome' => 'Harry Wilson', 
           'ds_abreviado' => 'Harry Wilson', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Fulham', 
           'ds_valor' => '17,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1198', 
           'nr_fim_random' => '1207', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '125', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '20', 
           'ds_nome' => 'Daniel James', 
           'ds_abreviado' => 'Daniel James', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Fulham', 
           'ds_valor' => '16,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1208', 
           'nr_fim_random' => '1217', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '126', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '17', 
           'ds_nome' => 'Sorba Thomas', 
           'ds_abreviado' => 'Sorba Thomas', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Huddersfield Town', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1218', 
           'nr_fim_random' => '1227', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '127', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '11', 
           'ds_nome' => 'Gareth Bale', 
           'ds_abreviado' => 'Gareth Bale ', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Los Angeles FC', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1228', 
           'nr_fim_random' => '1237', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '128', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '9', 
           'ds_nome' => 'Brennan Johnson', 
           'ds_abreviado' => 'Brennan Johnson', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Nottingham Forest', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1238', 
           'nr_fim_random' => '1247', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '129', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '13', 
           'ds_nome' => 'Kieffer Moore', 
           'ds_abreviado' => 'Kieffer Moore', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AFC Bournemouth', 
           'ds_valor' => '4,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1248', 
           'nr_fim_random' => '1257', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '130', 
           'id_selecao' => '8', 
           'ds_selecao' => 'País de Gales', 
           'ds_numero' => '19', 
           'ds_nome' => 'Mark Harris', 
           'ds_abreviado' => 'Mark Harris', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Cardiff City', 
           'ds_valor' => '1,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1258', 
           'nr_fim_random' => '1267', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '131', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '1', 
           'ds_nome' => 'Wojciech Szczesny', 
           'ds_abreviado' => 'Wojciech Szczesny', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '15,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1268', 
           'nr_fim_random' => '1277', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '132', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '22', 
           'ds_nome' => 'Bartlomiej Dragowski', 
           'ds_abreviado' => 'Bartlomiej Dragowski', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Spezia Calcio', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1278', 
           'nr_fim_random' => '1287', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '133', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '12', 
           'ds_nome' => 'Lukasz Skorupski', 
           'ds_abreviado' => 'Lukasz Skorupski', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Bologna', 
           'ds_valor' => '4,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1288', 
           'nr_fim_random' => '1297', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '134', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '5', 
           'ds_nome' => 'Jan Bednarek', 
           'ds_abreviado' => 'Jan Bednarek', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Aston Villa FC', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1298', 
           'nr_fim_random' => '1307', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '135', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '3', 
           'ds_nome' => 'Jakub Kiwior', 
           'ds_abreviado' => 'Jakub Kiwior', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Spezia Calcio', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1308', 
           'nr_fim_random' => '1317', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '136', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '6', 
           'ds_nome' => 'Mateusz Wieteska', 
           'ds_abreviado' => 'Mateusz Wieteska', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Clermont Foot 63', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1318', 
           'nr_fim_random' => '1327', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '137', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '15', 
           'ds_nome' => 'Kamil Glik', 
           'ds_abreviado' => 'Kamil Glik', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Benevento Calcio', 
           'ds_valor' => '1,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1328', 
           'nr_fim_random' => '1337', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '138', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '26', 
           'ds_nome' => 'Artur Jedrzejczyk', 
           'ds_abreviado' => 'Artur Jedrzejczyk ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Legia de Varsóvia', 
           'ds_valor' => '200 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1338', 
           'nr_fim_random' => '1347', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '139', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '2', 
           'ds_nome' => 'Matty Cash', 
           'ds_abreviado' => 'Matty Cash', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Aston Villa FC', 
           'ds_valor' => '22,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1348', 
           'nr_fim_random' => '1357', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '140', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '18', 
           'ds_nome' => 'Bartosz Bereszynski', 
           'ds_abreviado' => 'Bartosz Bereszynski', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'UC Sampdoria', 
           'ds_valor' => '4,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1358', 
           'nr_fim_random' => '1367', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '141', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '4', 
           'ds_nome' => 'Robert Gumny', 
           'ds_abreviado' => 'Robert Gumny', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Augsburgo', 
           'ds_valor' => '3,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1368', 
           'nr_fim_random' => '1377', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '142', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '10', 
           'ds_nome' => 'Grzegorz Krychowiak', 
           'ds_abreviado' => 'Grzegorz Krychowiak', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Al-Shabab Club (Riyadh)', 
           'ds_valor' => '8,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1378', 
           'nr_fim_random' => '1387', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '143', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '25', 
           'ds_nome' => 'Krystian Bielik', 
           'ds_abreviado' => 'Krystian Bielik', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Birmingham City', 
           'ds_valor' => '3,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1388', 
           'nr_fim_random' => '1397', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '144', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '13', 
           'ds_nome' => 'Szymon Zurkowski', 
           'ds_abreviado' => 'Szymon Zurkowski', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'ACF Fiorentina', 
           'ds_valor' => '7,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1398', 
           'nr_fim_random' => '1407', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '145', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '8', 
           'ds_nome' => 'Damian Szymanski', 
           'ds_abreviado' => 'Damian Szymanski', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AEK Atenas', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1408', 
           'nr_fim_random' => '1417', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '146', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '14', 
           'ds_nome' => 'Przemyslaw Frankowski', 
           'ds_abreviado' => 'Przemyslaw Frankowski', 
           'ds_posicao' => 'Meia Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RC Lens', 
           'ds_valor' => '7,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1418', 
           'nr_fim_random' => '1427', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '147', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '21', 
           'ds_nome' => 'Nicola Zalewski', 
           'ds_abreviado' => 'Nicola Zalewski', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AS Roma', 
           'ds_valor' => '12,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1428', 
           'nr_fim_random' => '1437', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '148', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '20', 
           'ds_nome' => 'Piotr Zielinski', 
           'ds_abreviado' => 'Piotr Zielinski', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Napoli', 
           'ds_valor' => '40,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1438', 
           'nr_fim_random' => '1447', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '149', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '19', 
           'ds_nome' => 'Sebastian Szymanski', 
           'ds_abreviado' => 'Sebastian Szymanski', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Feyenoord', 
           'ds_valor' => '14,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1448', 
           'nr_fim_random' => '1457', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '150', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '17', 
           'ds_nome' => 'Jakub Kaminski', 
           'ds_abreviado' => 'Jakub Kaminski', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VfL Wolfsburgo', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1458', 
           'nr_fim_random' => '1467', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '151', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '11', 
           'ds_nome' => 'Kamil Grosicki', 
           'ds_abreviado' => 'Kamil Grosicki', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Pogon Szczecin', 
           'ds_valor' => '600 mil € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1468', 
           'nr_fim_random' => '1477', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '152', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '24', 
           'ds_nome' => 'Michal Skoras', 
           'ds_abreviado' => 'Michal Skoras', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'KKS Lech Poznan', 
           'ds_valor' => '2,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1478', 
           'nr_fim_random' => '1487', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '153', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '9', 
           'ds_nome' => 'Robert Lewandowski', 
           'ds_abreviado' => 'Robert Lewandowski ', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Barcelona', 
           'ds_valor' => '45,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1488', 
           'nr_fim_random' => '1490', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '154', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '23', 
           'ds_nome' => 'Krzysztof Piatek', 
           'ds_abreviado' => 'Krzysztof Piatek', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Salernitana Calcio 1919', 
           'ds_valor' => '12,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1491', 
           'nr_fim_random' => '1500', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '155', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '7', 
           'ds_nome' => 'Arkadiusz Milik', 
           'ds_abreviado' => 'Arkadiusz Milik', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Juventus FC', 
           'ds_valor' => '10,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1501', 
           'nr_fim_random' => '1510', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '156', 
           'id_selecao' => '12', 
           'ds_selecao' => 'Polônia', 
           'ds_numero' => '16', 
           'ds_nome' => 'Karol Swiderski', 
           'ds_abreviado' => 'Karol Swiderski', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Charlotte FC', 
           'ds_valor' => '5,00 mi. €', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1511', 
           'nr_fim_random' => '1520', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '157', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '22', 
           'ds_nome' => 'Marc-André ter Stegen', 
           'ds_abreviado' => 'Marc-André ter Stegen', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Barcelona', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1521', 
           'nr_fim_random' => '1530', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '158', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '1', 
           'ds_nome' => 'Manuel Neuer', 
           'ds_abreviado' => 'Manuel Neuer ', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '12,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1531', 
           'nr_fim_random' => '1533', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '159', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '12', 
           'ds_nome' => 'Kevin Trapp', 
           'ds_abreviado' => 'Kevin Trapp', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Eintracht Frankfurt', 
           'ds_valor' => '8,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1534', 
           'nr_fim_random' => '1543', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '160', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '2', 
           'ds_nome' => 'Antonio Rüdiger', 
           'ds_abreviado' => 'Antonio Rüdiger', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '40,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1544', 
           'nr_fim_random' => '1549', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '161', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '15', 
           'ds_nome' => 'Niklas Süle', 
           'ds_abreviado' => 'Niklas Süle', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1550', 
           'nr_fim_random' => '1559', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '162', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '23', 
           'ds_nome' => 'Nico Schlotterbeck', 
           'ds_abreviado' => 'Nico Schlotterbeck', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '33,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1560', 
           'nr_fim_random' => '1569', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '163', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '5', 
           'ds_nome' => 'Thilo Kehrer', 
           'ds_abreviado' => 'Thilo Kehrer', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'West Ham United', 
           'ds_valor' => '22,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1570', 
           'nr_fim_random' => '1579', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '164', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '4', 
           'ds_nome' => 'Matthias Ginter', 
           'ds_abreviado' => 'Matthias Ginter', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SC Freiburg', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1580', 
           'nr_fim_random' => '1589', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '165', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '17', 
           'ds_nome' => 'Armel Bella-Kotchap', 
           'ds_abreviado' => 'Armel Bella-Kotchap', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Southampton', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1590', 
           'nr_fim_random' => '1599', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '166', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '16', 
           'ds_nome' => 'Lukas Klostermann', 
           'ds_abreviado' => 'Lukas Klostermann', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RB Leipzig', 
           'ds_valor' => '14,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1600', 
           'nr_fim_random' => '1609', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '167', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '3', 
           'ds_nome' => 'David Raum', 
           'ds_abreviado' => 'David Raum', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RB Leipzig', 
           'ds_valor' => '26,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1610', 
           'nr_fim_random' => '1619', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '168', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '26', 
           'ds_nome' => 'Christian Günter', 
           'ds_abreviado' => 'Christian Günter', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'SC Freiburg', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1620', 
           'nr_fim_random' => '1629', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '169', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '6', 
           'ds_nome' => 'Joshua Kimmich', 
           'ds_abreviado' => 'Joshua Kimmich', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '80,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1630', 
           'nr_fim_random' => '1635', 
           'tp_jogador' => 'S', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '170', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '8', 
           'ds_nome' => 'Leon Goretzka', 
           'ds_abreviado' => 'Leon Goretzka', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '65,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1636', 
           'nr_fim_random' => '1645', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '171', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '21', 
           'ds_nome' => 'Ilkay Gündogan', 
           'ds_abreviado' => 'Ilkay Gündogan', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Manchester City FC', 
           'ds_valor' => '25,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1646', 
           'nr_fim_random' => '1655', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '172', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '14', 
           'ds_nome' => 'Jamal Musiala', 
           'ds_abreviado' => 'Jamal Musiala', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '100,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1656', 
           'nr_fim_random' => '1665', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '173', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '7', 
           'ds_nome' => 'Kai Havertz', 
           'ds_abreviado' => 'Kai Havertz', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1666', 
           'nr_fim_random' => '1675', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '174', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '20', 
           'ds_nome' => 'Julian Brandt', 
           'ds_abreviado' => 'Julian Brandt', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '28,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1676', 
           'nr_fim_random' => '1685', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '175', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '19', 
           'ds_nome' => 'Mario Götze', 
           'ds_abreviado' => 'Mario Götze', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Eintracht Frankfurt', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1686', 
           'nr_fim_random' => '1695', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '176', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '11', 
           'ds_nome' => 'Leroy Sané', 
           'ds_abreviado' => 'Leroy Sané', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '70,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1696', 
           'nr_fim_random' => '1705', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '177', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '10', 
           'ds_nome' => 'Serge Gnabry', 
           'ds_abreviado' => 'Serge Gnabry', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '65,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1706', 
           'nr_fim_random' => '1715', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '178', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '9', 
           'ds_nome' => 'Karim Adeyemi', 
           'ds_abreviado' => 'Karim Adeyemi ', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '35,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1716', 
           'nr_fim_random' => '1725', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '179', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '18', 
           'ds_nome' => 'Jonas Hofmann', 
           'ds_abreviado' => 'Jonas Hofmann', 
           'ds_posicao' => 'Ponta Direita', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Mönchengladbach', 
           'ds_valor' => '13,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1726', 
           'nr_fim_random' => '1735', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '180', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '13', 
           'ds_nome' => 'Thomas Müller', 
           'ds_abreviado' => 'Thomas Müller ', 
           'ds_posicao' => 'Seg. Atacante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1736', 
           'nr_fim_random' => '1745', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '181', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '25', 
           'ds_nome' => 'Youssoufa Moukoko', 
           'ds_abreviado' => 'Youssoufa Moukoko', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Borussia Dortmund', 
           'ds_valor' => '30,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1746', 
           'nr_fim_random' => '1755', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '182', 
           'id_selecao' => '19', 
           'ds_selecao' => 'Alemanha', 
           'ds_numero' => '24', 
           'ds_nome' => 'Niclas Füllkrug', 
           'ds_abreviado' => 'Niclas Füllkrug', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Werder Bremen', 
           'ds_valor' => '5,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1756', 
           'nr_fim_random' => '1765', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '183', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '1', 
           'ds_nome' => 'Dominik Livakovic', 
           'ds_abreviado' => 'Dominik Livakovic', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'GNK Dinamo Zagreb', 
           'ds_valor' => '8,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1766', 
           'nr_fim_random' => '1775', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '1', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '184', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '23', 
           'ds_nome' => 'Ivica Ivusic', 
           'ds_abreviado' => 'Ivica Ivusic', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'NK Osijek', 
           'ds_valor' => '5,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1776', 
           'nr_fim_random' => '1785', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '23', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '185', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '12', 
           'ds_nome' => 'Ivo Grbic', 
           'ds_abreviado' => 'Ivo Grbic', 
           'ds_posicao' => 'Goleiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atlético de Madrid', 
           'ds_valor' => '3,50 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '1', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1786', 
           'nr_fim_random' => '1795', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '12', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '186', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '20', 
           'ds_nome' => 'Josko Gvardiol', 
           'ds_abreviado' => 'Josko Gvardiol', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'RB Leipzig', 
           'ds_valor' => '60,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1796', 
           'nr_fim_random' => '1805', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '20', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '187', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '25', 
           'ds_nome' => 'Josip Sutalo', 
           'ds_abreviado' => 'Josip Sutalo', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'GNK Dinamo Zagreb', 
           'ds_valor' => '18,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1806', 
           'nr_fim_random' => '1815', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '25', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '188', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '5', 
           'ds_nome' => 'Martin Erlic', 
           'ds_abreviado' => 'Martin Erlic', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'US Sassuolo', 
           'ds_valor' => '5,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1816', 
           'nr_fim_random' => '1825', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '5', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '189', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '6', 
           'ds_nome' => 'Dejan Lovren', 
           'ds_abreviado' => 'Dejan Lovren', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Zenit São Petersburgo', 
           'ds_valor' => '4,50 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1826', 
           'nr_fim_random' => '1835', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '6', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '190', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '21', 
           'ds_nome' => 'Domagoj Vida', 
           'ds_abreviado' => 'Domagoj Vida ', 
           'ds_posicao' => 'Zagueiro', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'AEK Atenas', 
           'ds_valor' => '2,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '2', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1836', 
           'nr_fim_random' => '1845', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '21', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '191', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '19', 
           'ds_nome' => 'Borna Sosa', 
           'ds_abreviado' => 'Borna Sosa', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'VfB Stuttgart', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1846', 
           'nr_fim_random' => '1855', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '19', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '192', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '3', 
           'ds_nome' => 'Borna Barisic', 
           'ds_abreviado' => 'Borna Barisic', 
           'ds_posicao' => 'Lateral Esq.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Rangers FC', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '4', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1856', 
           'nr_fim_random' => '1865', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '3', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '193', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '2', 
           'ds_nome' => 'Josip Stanisic', 
           'ds_abreviado' => 'Josip Stanisic ', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'FC Bayern de Munique', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1866', 
           'nr_fim_random' => '1875', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '2', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '194', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '22', 
           'ds_nome' => 'Josip Juranovic', 
           'ds_abreviado' => 'Josip Juranovic', 
           'ds_posicao' => 'Lateral Dir.', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Celtic FC', 
           'ds_valor' => '7,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '3', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1876', 
           'nr_fim_random' => '1885', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '22', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '195', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '11', 
           'ds_nome' => 'Marcelo Brozovic', 
           'ds_abreviado' => 'Marcelo Brozovic', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Inter de Milão', 
           'ds_valor' => '40,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1886', 
           'nr_fim_random' => '1895', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '11', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '196', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '26', 
           'ds_nome' => 'Kristijan Jakic', 
           'ds_abreviado' => 'Kristijan Jakic', 
           'ds_posicao' => 'Volante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Eintracht Frankfurt', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '5', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1896', 
           'nr_fim_random' => '1905', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '26', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '197', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '8', 
           'ds_nome' => 'Mateo Kovacic', 
           'ds_abreviado' => 'Mateo Kovacic', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Chelsea FC', 
           'ds_valor' => '40,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1906', 
           'nr_fim_random' => '1915', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '8', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '198', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '24', 
           'ds_nome' => 'Luka Sucic', 
           'ds_abreviado' => 'Luka Sucic', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Red Bull Salzburgo', 
           'ds_valor' => '20,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1916', 
           'nr_fim_random' => '1925', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '24', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '199', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '10', 
           'ds_nome' => 'Luka Modric', 
           'ds_abreviado' => 'Luka Modric ', 
           'ds_posicao' => 'Meia Central', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Real Madrid CF', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '6', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1926', 
           'nr_fim_random' => '1928', 
           'tp_jogador' => 'G', 
           'nr_camisa' => '10', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '200', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '4', 
           'ds_nome' => 'Ivan Perisic', 
           'ds_abreviado' => 'Ivan Perisic', 
           'ds_posicao' => 'Meia Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Tottenham Hotspur ', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '7', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1929', 
           'nr_fim_random' => '1938', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '4', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '201', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '15', 
           'ds_nome' => 'Mario Pasalic', 
           'ds_abreviado' => 'Mario Pasalic', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Atalanta BC', 
           'ds_valor' => '28,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1939', 
           'nr_fim_random' => '1948', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '15', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '202', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '7', 
           'ds_nome' => 'Lovro Majer', 
           'ds_abreviado' => 'Lovro Majer', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Stade Rennais FC', 
           'ds_valor' => '22,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1949', 
           'nr_fim_random' => '1958', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '7', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '203', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '13', 
           'ds_nome' => 'Nikola Vlasic', 
           'ds_abreviado' => 'Nikola Vlasic', 
           'ds_posicao' => 'Meia Ofensivo', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'Torino FC', 
           'ds_valor' => '22,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '9', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1959', 
           'nr_fim_random' => '1968', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '13', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '204', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '18', 
           'ds_nome' => 'Mislav Orsic', 
           'ds_abreviado' => 'Mislav Orsic', 
           'ds_posicao' => 'Ponta Esquerda', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'GNK Dinamo Zagreb', 
           'ds_valor' => '10,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '8', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1969', 
           'nr_fim_random' => '1978', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '18', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '205', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '9', 
           'ds_nome' => 'Andrej Kramaric', 
           'ds_abreviado' => 'Andrej Kramaric', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'TSG 1899 Hoffenheim', 
           'ds_valor' => '9,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1979', 
           'nr_fim_random' => '1988', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '9', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '206', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '14', 
           'ds_nome' => 'Marko Livaja', 
           'ds_abreviado' => 'Marko Livaja', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'HNK Hajduk Split', 
           'ds_valor' => '8,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1989', 
           'nr_fim_random' => '1998', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '14', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '207', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '16', 
           'ds_nome' => 'Bruno Petkovic', 
           'ds_abreviado' => 'Bruno Petkovic', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'GNK Dinamo Zagreb', 
           'ds_valor' => '6,00 mi. €  ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '1999', 
           'nr_fim_random' => '2008', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '16', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '208', 
           'id_selecao' => '24', 
           'ds_selecao' => 'Croácia', 
           'ds_numero' => '17', 
           'ds_nome' => 'Ante Budimir', 
           'ds_abreviado' => 'Ante Budimir', 
           'ds_posicao' => 'Centroavante', 
           'dt_nascimento' => '1901-01-01', 
           'ds_time' => 'CA Osasuna', 
           'ds_valor' => '6,00 mi. € ', 
           'created_at' => Carbon::now(), 
           'updated_at' => Carbon::now(), 
           'id_posicao' => '10', 
           'vl_preco' => '0', 
           'nr_ini_random' => '2009', 
           'nr_fim_random' => '2018', 
           'tp_jogador' => 'N', 
           'nr_camisa' => '17', 
       ]);
       DB::table('jogadores')->insert([
           'id' => '0', 
       ]);
   }
}