pipeline {
    agent { dockerfile true }    
    stages {
        stage('build'){
            steps{
                checkout scm                
            }
        }
        stage('Test') {
            steps {
                sh 'php --version'      
                sh 'ls -ltr'
                sh './vendor/bin/phpstan analyse --memory-limit=2G'          
            }
        }
    }
}