pipeline {
 agent any
 stages {
        stage("Build") {
            steps {                
                sh 'docker compose up --detach'
            }
        }
        stage("Unit test") {
            steps {
                sh 'php artisan test'
            }
        }
  }
}